image: node:latest

# Cache modules in between jobs per-branch
cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - npm install

test:
  stage: test
  tags:
    - docker
  script:
    - npm run ci-test

deploy:
  only:
    - main
  image: ruby:3.3.0
  tags:
    - docker
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
